# Generated by Django 5.1.1 on 2024-10-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_merge_0003_alter_car_id_0003_car_image_url'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.car'),
            preserve_default=False,
        ),
    ]
