# Generated by Django 5.1.1 on 2024-10-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_car'),
        ('wishlist', '0003_alter_wishlist_id'),
    ]

    operations = [
    ]
