# Generated by Django 5.1.1 on 2024-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Rendah'), (2, 'Sedang'), (3, 'Tinggi')], default=1),
        ),
    ]
