# Generated by Django 5.1.1 on 2024-10-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_car_seller_buat_dashboard_alter_car_seller'),
        ('wishlist', '0004_merge_0002_wishlist_car_0003_alter_wishlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.car'),
        ),
    ]
