# Generated by Django 5.1.2 on 2024-10-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_priority'),
        ('wishlist', '0005_alter_wishlist_car'),
    ]

    operations = [
    ]
