# Generated by Django 5.1.2 on 2024-10-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('UM', 'Umum'), ('JB', 'Jual Beli'), ('TT', 'Tips & Tricks'), ('SA', 'Santai')], default='UM', max_length=2),
        ),
    ]
