# Generated by Django 5.1.2 on 2024-10-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_question_category'),
        ('product_catalog', '0004_merge_0003_alter_car_id_0003_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.car'),
        ),
    ]
