# Generated by Django 5.1.2 on 2024-10-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_alter_car_id'),
        ('product_catalog', '0003_car_image_url'),
    ]

    operations = [
    ]
