# Generated by Django 5.1.1 on 2024-10-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0007_alter_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='seller_buat_dashboard',
        ),
    ]
